home:
    resource: "@TemplateHomeBundle/config/routes.yaml"
    host: '%domain%'

controllers:
    resource:
        path: ../src/Controller/
        namespace: Template\Controller
    type: attribute
